services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env.template
    depends_on:
      - db
    volumes:
      - volume-data:/data/

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: sample-fse
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - volume-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  volume-data:
    driver: local